library(RPostgreSQL)
library(ggplot2)
drv <- dbDriver('PostgreSQL')
con <- dbConnect(drv, dbname='msrb', user='postgres', password='A1b2c3d4')
munitrades <-dbReadTable(con,'munitrades_unique')
qplot(price_inter, data=munitrades, geom="histogram")
attacch(munitrades)
summary(price_inter)
fivenum(price_inter)
stem(price_inter)